# -*- coding: utf-8 -*-
"""04-VISUAL-AMALIYOT-04-distribution-JAVOBLAR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cihy-QGigtpiZb5n9FZ-z8jFzPbgXpqU

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 4-MODUL. VIZUALIZASIYA

## 4-AMALIYOT. Distribution
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""### Ushbu amaliyotda uybor.uz saytidan yuklab olingan ma'lumotlar tahlili bilan shu'gullanamiz."""

df = pd.read_csv("https://github.com/jamshid-ds/praktikum_datasets/blob/main/uybor_scrapping.csv?raw=true")
df.head()

"""#### Yuqoridagi jadvalda Toshkent shahridagi sotildagian uylar haqida ma'lumotlar jamlangan.

### 1-VAZIFA. Uylarning narxi taqsimotini grafikda ko'rsating
"""

#JAVOBINGIZNI SHUYERGA YOZING
plt.figure(figsize=(10,6))
sns.histplot(data=df, x="price" )
plt.show()

"""### Jadvalda 7000 dan oshiq uy bor, aksar uylarning narxi 200000$ dan kam. Keling noodatiy katta qiymatlarni tashlab yuboramiz va yuqoridagi chizmani qaytadan chizamiz."""

#JAVOBINGIZNI SHUYERGA YOZING
df = df[df.price<=200_000]
plt.figure(figsize=(10,6))
sns.histplot(data=df, x="price" )
plt.show()

"""### 2-VAZIFA. Uylarning maydoni taqsimoti grafigini chizing"""

# JAVOB UCHUN JOY
plt.figure(figsize=(10,6))
sns.histplot(data=df, x="size")
plt.show()

"""### 3-VAZIFA. Uylarning xonalar soni taqsimotini chiqaring."""

# JAVOB UCHUN JOY
plt.figure(figsize=(10,6))
sns.histplot(data=df, x="rooms")
plt.show()

"""6 xonadan ortiq uylarni tashlab yuboramiz."""

df = df[df['rooms']<7]

"""### 4-VAZIFA. Uylarning narxi taqsimotini xonalar soniga bog'lab chiqaramiz."""

# JAVOBNI SHUYERGA YOZING
sns.displot(data=df, x="price",hue="rooms", height=5, aspect=2,palette="Accent" )
plt.show()

"""### 4.1 Grafik tushunarsiz chiqdi. Keling faqatgina 1,2,3 xonali uylarning narx bo'yicha taqsimotini chizamiz."""

# JAVOBNI SHUYERGA YOZING
sns.displot(data=df[df.rooms<4], x="price",hue='rooms',multiple='stack',palette='Reds',height=5,aspect=2 )
plt.show()

"""### 5-VAZIFA. 4,5,6 xonali uylar uchun narx taqsimotini alohida grafiklarda chizing"""

# JAVOB UCHUN JOY
sns.displot(data=df[df['rooms']>=4], x='price', col='rooms', height=5, aspect=1)
plt.show()

"""## 6-VAZIFA. Uylarning maydoni taqsimoti KDE grafigini chizing"""

# JAVOB UCHUN JOY
sns.displot(data=df, x='size', kind='kde',height=5,aspect=2)
plt.xticks(rotation=90)
plt.show()

"""## 7-VAZIFA. Uylarning maydoni taqsimotini KDE va taqsimotini birlashtirib chizing."""

# JAVOB UCHUN JOY
sns.displot(data=df, x='size',kde='True', height=5,aspect=2)
plt.show()

"""## 8-VAZIFA. Uylarning narxi va xonalari soni uchun (2,3,5 xonali) KDE chizing."""

# JAVOB UCHUN JOY
plt.figure(figsize=(10,5))
sns.kdeplot(data=df[df['rooms'].isin([2,3,5])], x='price', hue='rooms', shade=True)
plt.xticks(rotation=90)
plt.show()

"""## 9-VAZIFA. Uylarning maydoni uchun kumulyativ taqsimot grafigini chizing (CDF)"""

sns.displot(data=df, x="size", kind="ecdf", height=5, aspect=2)
plt.xticks(rotation=90)
plt.grid(which='both') # setka (major, minor, both) qiymatlarini berib ko'ring
plt.minorticks_on()
plt.show()

"""## 10-VAZIFA. Yuqoridagi grafikni uylarning narxi uchun chizing."""

# JAVOB UCHUN JOY
sns.displot(data=df, x="price", kind="ecdf", height=5, aspect=2)
plt.xticks(rotation=90)
plt.grid(which='both')
plt.minorticks_on()
plt.show()