# -*- coding: utf-8 -*-
"""04-VISUAL-AMALIYOT-01-matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jzhJ1gN6msILYOHaG2fhBBvUGaa4tcLf

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 4-MODUL. VIZUALIZASIYA

## 1-AMALIYOT. `matplotlib`
"""

import pandas as pd
import numpy as np

"""Ushbu amaliyot uchun https://en.tutiempo.net/climate/ws-384570.html sahifasidagi Toshkent shahri o'rtacha havo harorati haqidagi ma'lumotlardan foydalanamiz.

![](https://i.imgur.com/lCIRIYm.png)
"""

#@title QUYIDAGI KODGA TEGMANG!!!
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

"""## 1-VAZIFA: Sahifadagi jadvalni pandas dataframega aylantiring va:
### - Yil (`Year`) ustunini index sifatida o'qing.
### - 1990 yildan avvalgi ma'lumotlar tashlab yuboring.
### - natijani `df` degan o'zgaruvchiga saqlang
"""

# JAVOBNI SHUYERGA YOZING
tables = pd.read_html("https://en.tutiempo.net/climate/ws-384570.html", index_col=0)
df = tables[3]
df = df[df.index>=1990]
df.head()

"""## 2-VAZIFA. Har bir ustun nimani anglatishi ham yuqoridagi sahifada joylashgan. Shu jadvalni ham chiqaring. Matnlarni [Google translate](https://translate.google.com) orqali tarjima qilib, uqib oling."""

# JAVOBNI SHUYERGA YOZING
tables[4]

"""## 3-VAZIFA. `df`ni tahlil qilamiz"""

df.info()

"""### **SAVOL**: Yuqoridagi natijadan qanday xulosaga kelish mumkin? DF dagi sonlar bilan ishlasak bo'ladimi?"""

#@title JAVOB:
# Afsuski, jadvalda mavjud bo'lmagan qiymatlar o'rniga tire (-) belgisi qo'yib ketilgan,
# shu sababdan jadval ustunlari son (int, float) emas matn (object) bo'lib qolgan.

"""## 4-VAZIFA. `df`dagi barcha `-` belgilarni `NaN` qiymat bilan almashtiring."""

# JAVOBNI SHUYERGA YOZING
df.replace("-",np.NaN, inplace=True)

"""## 5-VAZIFA. `df` ustunlari qiymatlarini matndan o'nlik songa (`float`) o'zgartiring."""

# JAVOBNI SHUYERGA YOZING
df = df.astype(dtype='float')
df.head(10)

"""## 6-VAZIFA. `NaN` qiymatlar bilan ishlaymiz
### 6.1. Har bir ustundagi `NaN` qiymatlar soni va ularning proprosiyasini toping.
"""

# JAVOBNI SHUYERGA YOZING
df.isnull().sum()/len(df)*100

"""### 6.2. Eng ko'p `nan` qiymat mavjud ustunni tashlab yuboring va natijani saqlab qoling."""

# JAVOBNI SHUYERGA YOZING
df.drop("PP",inplace=True,axis=1)

"""### 6.3. Qolgan `NaN` qiymatlarni o'zingiz to'g'ri deb bilgan usulda to'ldiring (tashlab yubormang) va natijani saqlab qoling."""

# JAVOBNI SHUYERGA YOZING
df.fillna(method='ffill',inplace=True)
df.head()

"""### 6.4. Yakuniy `df` ni csv faylga saqlab, kompyuterga (yoki githubga) yuklab oling (keyingi darsda ishlatamiz)"""

# JAVOBNI SHUYERGA YOZING
df.to_csv("tashtemp.csv")

"""##7-VAZIFA. Chiziqli grafiklar

### 7.1. `df`dan yillik o'rtacha haroratni ko'rsatuvchi ustunni `x` o'zgaruvchiga saqlang va `plt.plot()` yordamida chiziqli grafik chizing.
"""

# Commented out IPython magic to ensure Python compatibility.
# JAVOBNI SHUYERGA YOZING
x=df['T']
import matplotlib.pyplot as plt
# %matplotlib inline
plt.plot(x)
plt.show()

"""### 7.2. Yuqoridagi grafikni hajmini kattalashtiring, chiziq qalingligi, turi, rangi, markerlar turini istalgancha o'zgartiring"""

# JAVOBNI SHUYERGA YOZING
plt.figure(figsize=(16,8))
plt.plot(x, linewidth=2, linestyle="--", marker='h', markerfacecolor='r')
plt.show()

"""### 7.3. Yuqoridagi grafikda x va y o'qlarini nomlang, grafikka ham umumiy nom bering"""

# JAVOBNI SHUYERGA YOZING

plt.figure(figsize=(16,8))
plt.plot(x, linewidth=2, linestyle="--", marker='h', markerfacecolor='r')
plt.title("TOSHKENT")
plt.xlabel("yillar")
plt.ylabel("Harorat")
plt.show()

#@title To'g'ri javob
x=df['T']
plt.figure(figsize=(16,8))
plt.plot(x, linewidth=2, linestyle="--", marker='h', markerfacecolor='r')
plt.title("Toshkent shahri uchun yillik o'rtacha harorat")
plt.xlabel("Yil")
plt.ylabel("Harorat")
plt.show()

"""## 8-VAZIFA. Toshkent shahri uchun, har bir yilda o'rtacha min va max haroratlarni ko'rsatuvchi grafik chizing. **Grafikni faylga saqlab oling**"""

# JAVOBNI SHUYERGA YOZING

minT = df['Tm']
maxT = df['TM']
plt.figure(figsize=(16,8))
plt.plot(minT, linewidth=2, linestyle="--", marker='h', markerfacecolor='g', label="O'rtacha minimum harorat")
plt.plot(maxT, linewidth=2, linestyle="-", marker='v', markerfacecolor='r', label="O'rtacha maksimum harorat")
plt.grid()
plt.legend(loc=0)
plt.title("Toshkent shahri uchun yillik o'rtacha min va max harorat")
plt.xlabel("Yil")
plt.ylabel("Harorat")
plt.savefig('tempMinMax.png')
plt.show()

#@title To'g'ri javob
minT = df['Tm']
maxT = df['TM']
plt.figure(figsize=(16,8))
plt.plot(minT, linewidth=2, linestyle="--", marker='h', markerfacecolor='g', label="O'rtacha minimum harorat")
plt.plot(maxT, linewidth=2, linestyle="-", marker='v', markerfacecolor='r', label="O'rtacha maksimum harorat")
plt.grid()
plt.legend()
plt.title("Toshkent shahri uchun yillik o'rtacha min va max harorat")
plt.xlabel("Yil")
plt.ylabel("Harorat")
plt.savefig('tempMinMax.png')
plt.show()

"""## 9-VAZIFA. Faylga saqlangan grafikni ochib ko'ring."""

# JAVOBNI SHUYERGA YOZING
from IPython.display import Image
Image('tempMinMax.png')