# -*- coding: utf-8 -*-
"""04-VISUAL-AMALIYOT-02-seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qy2Tj8VCE5gi1jD7u-hCh8amDSt5cGvm

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 4-MODUL. VIZUALIZASIYA

## 2-AMALIYOT. `seaborn`
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""### 1-VAZIFA. Avvalgi [amaliyotda](https://colab.research.google.com/drive/1jzhJ1gN6msILYOHaG2fhBBvUGaa4tcLf?usp=sharing) saqlangan faylni yangi `df`ga o'qing"""

#JAVOBINGIZNI SHU YERGA YOZING
df = pd.read_csv("tashtemp.csv", index_col=0)
df.head()

"""### 2-VAZIFA. `df` barcha ustunlarini chiziqli grafik ko'rinishida chiqaring"""

#JAVOBINGIZNI SHU YERGA YOZING
plt.figure(figsize=(16,6))
sns.lineplot(data=df)
plt.title("Toshkent shahri yillik ob-havo ko'rsatkichlari")
plt.xlabel("Yil")
plt.show()

"""### 3-VAZIFA. Grafiklar nomini to'g'rilang (`T`, `Tm` va hokazo matnlarni o'zbek tilida chiqaring.)"""

#JAVOBINGIZNI SHU YERGA YOZING
labels=["Yillik o'rtacha harorat",
        "Yillik o'rtacha maksimal harorat",
        "Yillik o'rtacha minimal harorat",
        "Yillik o'rtacha shamol tezligi",
        "Yomg'irli kunlar soni",
        "Bo'ronli kunlar soni",
        "Tumanli kunlar soni",
        "To'fonli kunlar soni",
        "Do'l yoqqan kunlar"
        ]
plt.figure(figsize=(16,6))
sns.lineplot(data=df, linewidth=2.0)
plt.title("Toshkent shahri uchun ob havo ko'rsatkichlari")
plt.xlabel("Yil")
plt.ylabel("Harorat")
plt.legend(labels, loc=1)
plt.show()

"""### 4-VAZIFA. Yuqoridagi grafikda turli ko'rsatkichlar aralashib ketdi. Keling ustun turiga qarab alohida grafiklar chizamiz.

#### 4.1. Haroratni ko'rsatuvchi ustunlarni alohida chiziqli grafik qilib chiqaring.
"""

#JAVOBINGIZNI SHU YERGA YOZING
labels=["Yillik o'rtacha harorat",
        "Yillik o'rtacha maksimal harorat",
        "Yillik o'rtacha minimal harorat",
        ]
plt.figure(figsize=(16,6))
sns.lineplot(data=df[["T","TM","Tm"]], linewidth=2.0)
plt.title("Toshkent shahri uchun ob havo ko'rsatkichlari")
plt.xlabel("Yil")
plt.ylabel("Harorat")
plt.legend(labels, loc=1)
plt.show()

"""#### 4.2. Kunlarni ko'rsatuvchi ustunlarni alohida grafik ko'rinishida chiqaring"""

#JAVOBINGIZNI SHU YERGA YOZING
labels=[
        "Yomg'irli kunlar soni",
        "Bo'ronli kunlar soni",
        "Tumanli kunlar soni",
        "To'fonli kunlar soni",
        "Do'l yoqqan kunlar soni"
        ]

plt.figure(figsize=(16,6))
sns.lineplot(data=df[['RA','SN','TS','FG','TN']], linewidth=2.0)
plt.title("Toshkent shahri uchun ob havo ko'rsatkichlari")
plt.xlabel("Yil")
plt.ylabel("Kunlar")
plt.legend(labels, loc=1)
plt.show()

"""### 5-VAZIFA. Yillik o'rtacha shamol tezligini ustunli grafik ko'rinishida chiqaring."""

#JAVOBINGIZNI SHU YERGA YOZING
plt.figure(figsize=(16,6))
sns.barplot(x=df.index, y=df['V'])
plt.title("Toshkent shahri uchun ob havo ko'rsatkichlari")
plt.ylabel("O'rtacha shamol tezligi (km/soat)")
plt.xlabel("Yillar")
plt.xticks(rotation=90)
plt.show()



"""### 6-VAZIFA. Yomg'rili, qorli, bo'ronli, tumanli va do'l yoqqan kunlar sonini heatmap ko'rinishida chiqaring."""

#JAVOBINGIZNI SHU YERGA YOZING
plt.figure(figsize=(30,5))
sns.heatmap(data=df[['RA','SN','TS','FG','GR']].T, cmap="YlGnBu", linewidths=1, square=True)
plt.title("Toshkent shahri uchun ob havo ko'rsatkichlari")
yticks_labels = ["Yomg'ir","Qor","Bo'ron","Tuman","Do'l"]
plt.yticks(np.arange(5)+0.5, labels=yticks_labels)
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.show()