# -*- coding: utf-8 -*-
"""Copy of 04-VISUAL-AMALIYOT-04-distribution-JAVOBLAR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pUPlg8ag5OrmoxR7qVY3KlIQ6IC5OgcE

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 4-MODUL. VIZUALIZASIYA

## 4-AMALIYOT. Distribution
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""### Ushbu amaliyotda uybor.uz saytidan yuklab olingan ma'lumotlar tahlili bilan shu'gullanamiz."""

df = pd.read_csv("https://github.com/jamshid-ds/praktikum_datasets/blob/main/uybor_scrapping.csv?raw=true")
df.head()

"""#### Yuqoridagi jadvalda Toshkent shahridagi sotildagian uylar haqida ma'lumotlar jamlangan.

## 1-VAZIFA. Jadvaldan xonalari 5 xonadan ko'p bo'lgan, narxi 200000 mingdan, maydoni 250kv.m dan ortiq bo'lgan uylarni tashlab yuboring
"""

df=df[df['rooms']<6]
df=df[df['size']<250]
df=df[df['price']<200000]
df.shape

"""## 2-VAZIFA. `subplot` yordamida uylarning narxi va xonalar soni taqsimoti grafiklarini yonma yon chizing"""

#JAVOBINGIZNI SHUYERGA YOZING
plt.figure(figsize=(16,8))
plt.subplot(1,2,1)
sns.histplot(data=df,x='price')
plt.subplot(1,2,2)
sns.histplot(data=df, x='size')
plt.show()

"""### 2-VAZIFA. Uylarning narxi taqsimoti va narx va maydoni o'rtasidagi bog'liqlik grafiklarini bitta chizmada ustma ust chiqaring."""

# JAVOB UCHUN JOY
fig, ax = plt.subplots(2,1, figsize=(10,6))
sns.histplot(ax=ax[0], data=df, x='price')
sns.scatterplot(ax=ax[1], data=df, x=df['size'], y=df['price'])
plt.show()

"""### 3-VAZIFA. Quyidagi grafikni chizing. Ahamiyat bering, oxirgi grafikda tumanlar bo'yicha uylarning o'rtacha narxi tasvirlangan."""

distdf = df.groupby('district').mean()
fig, ax = plt.subplots(2, 2, figsize=(15,10))
sns.histplot(ax=ax[0, 0], data=df, x='price')
sns.histplot(ax=ax[0, 1], data=df, x='size')
sns.scatterplot(ax=ax[1, 0], data=df, x=df['size'], y=df['price'])
sns.barplot(ax=ax[1, 1], x=distdf.index, y=distdf['price'])
ax[0,0].set_title("Uylarning narxi bo'yicha taqsimoti")
ax[0,1].set_title("Uylarning maydoni bo'yicha taqsimoti")
ax[1,0].set_title("Uylarning narxi va maydoni o'rtasioda bog'liqlik")
ax[1,1].set_title("Tumanlar bo'yicha o'rtacha narxlar")
plt.xticks(rotation=90)
plt.show()